from snakemake.utils import min_version

min_version("7.25.0")


include: "rules/common.smk"


module mapping_workflow:
    snakefile:
        github("xsitarcik/mapping", path="workflow/Snakefile", tag="v2.0.1")
    config:
        config


use rule * from mapping_workflow as mapping_*


include: "rules/indexing.smk"


for method in config["variants"]["callers"]:

    include: f"rules/variants/{method}.smk"


rule all:
    input:
        **mapping_workflow.get_outputs(),
        **get_outputs(),
    default_target: True
    localrule: True
