from snakemake.utils import min_version

min_version("7.25.0")

if os.path.exists(".parameters_parsed.txt"):
    os.remove(".parameters_parsed.txt")


include: "rules/common.smk"


module mapping_workflow:
    snakefile:
        github("xsitarcik/mapping", path="workflow/Snakefile", tag=config["module_versions"]["mapping"])
    config:
        config


use rule * from mapping_workflow as mapping_*


for method in config["variants"]["callers"]:

    include: f"rules/variants/{method}.smk"


for method in config["consensus"]["callers"]:

    include: f"rules/consensus/{method}.smk"


rule all:
    input:
        **mapping_workflow.get_outputs(),
        **get_outputs(),
    default_target: True
    localrule: True


with open(".parameters_parsed.txt", "a") as f:
    f.write(get_all_relevant_extra_params())
